# Development override for docker-compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  humid:
    environment:
      NODE_ENV: development
    volumes:
      # Mount source code for hot reload (if using nodemon)
      - ./apps/humid/src:/app/src
      - ./apps/humid/webpack.config.js:/app/webpack.config.js
    command: ["npm", "run", "humid:dev"]

  cloud:
    # In development, might want to serve from dev server instead
    # This would require a different Dockerfile or override
    environment:
      NODE_ENV: development
