# Development override for docker-compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  humid:
    environment:
      NODE_ENV: development
      # Add debug logging
      DEBUG: "*"
    # Override health check for development (less strict)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 45s
      timeout: 15s
      retries: 5
      start_period: 60s
    # Remove the command override to use the default from Dockerfile
    # volumes:
    #   # Only mount logs, not source code for now
    #   - ./logs:/app/logs

  cloud:
    # In development, might want to serve from dev server instead
    # This would require a different Dockerfile or override
    environment:
      NODE_ENV: development
